<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <RootNamespace>Alfred.Localization</RootNamespace>
    <AssemblyName>Alfred.Localization</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Languages\*.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Alfred.Localization.Tests" />
  </ItemGroup>

</Project>
