<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Alfred.Core</RootNamespace>
    <AssemblyName>Alfred.Core</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Alfred.Core.Tests" />
  </ItemGroup>

</Project>
