<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <RootNamespace>Alfred.App</RootNamespace>
    <AssemblyName>Alfred</AssemblyName>
    <IsPackable>false</IsPackable>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>Resources\Alfred.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\Alfred.ico" />
  </ItemGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' != ''">
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alfred.Core\Alfred.Core.csproj" />
  </ItemGroup>

</Project>
