<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <RootNamespace>Alfred.Update</RootNamespace>
    <AssemblyName>Alfred.Update</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alfred.Localization\Alfred.Localization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Alfred.Update.Tests" />
  </ItemGroup>

</Project>
